bool doPatches;

bool elecShock, slientAim, maxLevel, killAll, godmode, airJump, slowdownAll, speedupAll, floatHit, speedhack, spawnRacingCar, autoCar,
        dontRenderCar, nuke, spamChat, longLifetime, ricochet, gravity, polymorhp, tower, infScore, ammo, hideId, discord, currency, weapon, drawMenu,
        xpSpoofer, addAllGadgets,loopCur, ban, modUp, wepSkins6, freeBundle, unlockWear,
        disableJumpAll, effectSpam, setNickname, blackScreen, noClipAll, destroy, setAvatar, attractPlayers, handBug, destroyAuto, intLimitScore,
        xray, corruptedSniper, unlockCosmetics, startIllegalUnlockingWep, easyUnlockCos, easyUnlockWep, aimbot, teleKill, teamKill, noCharge, targetExplode,
        firerateHack, unlockCosmetics2, hello, floatAll, manualWeaponUnlock, unlockPet;

int selectedPrefab, rocketMode, resolutionIndex, selectedCur, curAmount, startWepIndex = 0, endWepIndex = 1, selectedAvatarRPC, selectedNickname,
    startCosIndex, endCosIndex, easyUnlockCosStep, easyUnlockWepStep, selectedRarity, weaponLevel = 65;

const char* hi;
float firerate;
void* currentWeaponSounds;
void* character;
void* WSMInstance;
std::string spam = "Nazi Mod - discord.gg/Y3gj2Rszq6";

using json = nlohmann::ordered_json;
std::unordered_map<int, std::unique_ptr<json>> commandParams = {};

monoList<void **> *players;
monoList<void**>* photonViewList;

void* keyboardPtr;
const char* manualUnlockInput = "ultimatum";

std::vector<void*> playerList;

const char* manualWeaponTypes[] =  {
    "Weapon", // 0
    "Wear", // 1
    "Gadget", // 2
    "Cosmetic", // 3
};
int manualWeaponType = 0;

enum PhotonTargets // TypeDefIndex: 7416
{
    All = 0,
    Others = 1,
    MasterClient = 2,
    AllBuffered = 3,
    OthersBuffered = 4,
    AllViaServer = 5,
    AllBufferedViaServer = 6,
    SelfViaServer = 7
};

enum EventEnum // TypeDefIndex: 9067
{
    ActivateMechRPC = 0,
    AddBonusAfterKillPlayerRPC = 1,
    AddForceRPC = 2,
    AddFreezerRayWithLength = 3,
    AddPaticleBazeRPC = 4,
    AddPlayerInCapturePoint = 5,
    AddScoreDuckHuntRPC = 6,
    AddWeaponAfterKillPlayerRPC = 7,
    AdvancedEffectRPC = 8,
    AdvancedEffectWithSenderRPC = 9,
    ApplyDamageRPC = 10,
    ApplyDebuffRPC = 11,
    ChargeGunAnimation = 12,
    ClearScoreCommandInFlagGameRPC = 13,
    Collide = 14,
    CountKillsCommandSynch = 15,
    CreateChestRPC = 16,
    DeactivateMechRPC = 17,
    DestroyRpc = 18,
    GetInPlayerRPC = 19,
    ShowSelectedFortNotification = 20,
    fireFlash = 21,
    GetBonusRewardRPC = 22,
    ActivateGadgetRPC = 23,
    GetDamageRPC = 24,
    RespawnRPC = 25,
    Go = 26,
    GoBazaRPC = 27,
    GoMatchRPC = 28,
    HoleRPC = 29,
    ImDeadInHungerGamesRPC = 30,
    imDeath = 31,
    ImKilledRPC = 32,
    IsVisible_RPC = 33,
    KilledByRPC = 34,
    LikeRPC = 35,
    MakeBonusRPC = 36,
    MeKillRPC = 37,
    OpponentLeftGame = 38,
    PlayDestroyEffectRpc = 39,
    PlayerEffectRPC = 40,
    PlayMusic = 41,
    PlayPortalSoundRPC = 42,
    PlayZombieAttackRPC = 43,
    PlayZombieRunRPC = 44,
    plusCountKillsCommand = 45,
    CheckActivityRPC = 46,
    HitByVehicleRPC = 47,
    ReloadGun = 48,
    RemoveBonusRPC = 49,
    RemoveBonusWithRewardRPC = 50,
    RemovePlayerInCapturePoint = 51,
    ResumeMatchRPC = 52,
    RevengeRequestRPC = 53,
    SendBuffParameters = 54,
    SendChatMessageWithIcon = 55,
    SendSystemMessegeFromFlagAddScoreRPC = 56,
    SendSystemMessegeFromFlagDroppedRPC = 57,
    SendSystemMessegeFromFlagReturnedRPC = 58,
    SetArmorVisInvisibleRPC = 59,
    setBootsRPC = 60,
    SetBotHealthRPC = 61,
    setCapeRPC = 62,
    SetCaptureRPC = 63,
    SetEnemyArmor = 64,
    SetEnemyBoots = 65,
    SetEnemyCape = 66,
    SetEnemyHat = 67,
    SetEnemyMask = 68,
    SetEnemyPet = 69,
    SetEnemySkin = 70,
    SetEnemyWeapon = 71,
    SetGadgetEffectActiveRPC = 72,
    SetGadgetesRPC = 73,
    SetHatWithInvisebleRPC = 74,
    SetBigHeadRPC = 75,
    SetJetpackEnabledRPC = 76,
    SetJetpackParticleEnabledRPC = 77,
    SetMaskRPC = 78,
    SetMyClanTexture = 79,
    SetMySkin = 80,
    SetNickName = 81,
    SetNOCaptureRPC = 82,
    SetPixelBookID = 83,
    SetRocketActive = 84,
    SetRocketActiveWithCharge = 85,
    SetRocketStickedRPC = 86,
    SetTargetRPC = 87,
    SetVisibleFireEffectRpc = 88,
    SetWeaponRPC = 89,
    SetWeaponSkinRPC = 90,
    SetWearIsInvisibleRPC = 91,
    ShotRPC = 92,
    ShowBonuseParticleRPC = 93,
    ShowExplosion = 94,
    ShowMultyKillRPC = 95,
    SinchCapture = 96,
    SlowdownRPC = 97,
    StartFlashRPC = 98,
    StartGame = 99,
    StartMatchRPC = 100,
    StartNewRespanObjectRpc = 101,
    StartRocketRPC = 102,
    StartShootLoopRPC = 103,
    StartTurretRPC = 104,
    SynchCaptureCounter = 105,
    SynchCaptureCounterNewPlayer = 106,
    SynchGameRating = 107,
    SynchGameTimer = 108,
    SynchNamberSpawnZoneRPC = 109,
    SynchNumUpdateRPC = 110,
    SynchronizeTimeRPC = 111,
    SynchScoreCommandRPC = 112,
    SynchScoresCommandsNewPlayerRPC = 113,
    SynchScoresCommandsRPC = 114,
    SynchStartTimer = 115,
    SynhCommandRPC = 116,
    SynhCountKillsRPC = 117,
    SynhDeltaHealthRPC = 118,
    SynhHealthRPC = 119,
    SynhIsZoming = 120,
    SynhNameRPC = 121,
    SynhRanksRPC = 122,
    SynhScoreRPC = 123,
    SynhDeltaArmorRPC = 124,
    PropertyRPC = 125,
    winInHungerRPC = 126,
    SetPlayerUniqID = 127,
    SynchLivesItems = 128,
    RegisterPlayerRPC = 129,
    SetGamemodeRPC = 130,
    SetMapRPC = 131,
    StartGameRPC = 132,
    SetReadyRPC = 133,
    QuitFromSquadRPC = 134,
    ShowStartGameRPC = 135,
    StartTimerRPC = 136,
    KickPlayerRPC = 137,
    SynchCurrentCategory = 138,
    ResetVersusTimerRPC = 139,
    StartAirDropItemRPC = 140,
    MakeBetRPC = 141,
    GoTeamMatchRPC = 142,
    StartTeamMatchRPC = 143,
    SynchronizeMatchTimeRPC = 144,
    SetRocketActiveWithNumSmoke = 145,
    SynhDeathCountRPC = 146,
    GoRevengeMatchRPC = 147,
    EndRoundRPC = 148,
    SynchronizeGoTimeRPC = 149,
    SyncronizeTeamWins = 150,
    FireFlashDamagebleRPC = 151,
    SetMaxArmorAndHealthRPC = 152,
    SendEmojiRPC = 153,
    SynchGetGadgets = 154,
    SyncTramPosition = 155,
    UnregisterPlayerRPC = 156,
    SyncLastMoveTime = 157,
    RemoveTargetRPC = 158,
    AttackGateRPC = 159,
    ShotArtilleryRPC = 160,
    SetDestinationRPC = 161,
    SetEquipRPC = 162,
    ShowEndEventRPC = 163,
    ShowEndEventNotificationRPC = 164,
    PlayingInSquadRPC = 165,
    SynchCombatLevelRPC = 166,
    SendPetIdRPC = 167,
    SynchGameLeague = 168,
    ActiveChunkChangedRPC = 169,
    GetBonusRPC = 170,
    SetGliderRPC = 171,
    AddWeaponAfterBonusPreviewRPC = 172,
    RemoveWeaponPreviewRPC = 173,
    SetRoyaleAvatarRPC = 174,
    SetMapPositionSquadRPC = 175,
    PlayerInjuredRPC = 176,
    SynhHealthInjuredRPC = 177,
    PlayerInjuryHealedRPC = 178,
    SetLandingTrailRPC = 179,
    SetUserMapMarkerRPC = 180,
    RemoveUserMapMarkerRPC = 181,
    FlyOnGliderSynchRPC = 182,
    BattleRoyaleSquadMemberKilledRPC = 183,
    HealingByPlayerRPC = 184,
    PlayerInjuryHealingProgressRPC = 185,
    WinRequestRPC = 186,
    SetMyAvatar = 187,
    SetEnemyAvatar = 188,
    SetEquipTypeRPC = 189,
    SynchMinigunRotationRPC = 190,
    PlayZombieBeforeAttackRPC = 191,
    SendNewEmojiRPC = 192,
    SynchVehicleParamsRPC = 193,
    SendBattleEmojiRPC = 194,
    SynchVehicleColorRPC = 195,
    SendChangeMobRPC = 196,
    EnterInTrigger = 197,
    SynchWeaponModulesRPC = 198,
    SynchArmorModulesRPC = 199,
    SetModuleGadgetEffectActiveRPC = 200,
    CreateRocketRPC = 201,
    ShowEffectOnOtherPlayersRPC = 202,
    SetParticleToWeaponRPC = 203,
    RegenerateHealthMob = 204,
    SendKillMob = 205,
    SynhDeltaHealthFromWeaponRPC = 206,
    JumpDisableRPC = 207,
    SetPortalRPC = 208,
    ActivatePolymorphRPC = 209,
    DeactivatePolymorphRPC = 210,
    AlternativeMobAttack = 211,
    AlternativeMobShot = 212,
    DetonateKamikadze = 213,
    SetWeaponLevel = 214,
    MarkEnemy = 215,
    GetDamageToShieldRPC = 216,
    SendOnGroundEffect = 217,
    PluginRPC = 218,
    EnableTeleportEffectsRPC = 219,
    AddAmmoFromWeaponRPC = 220,
    KillerInvisiblityRPC = 221,
    SyncGadgetReflectorCoeffRPC = 222,
    SynchVipStatusRPC = 223,
    InviteToSquadRPC = 224,
    JoinSquadRPC = 225,
    InviteToSquadFailRPC = 226,
    SyncBreakableObjects = 227,
    FreeFallSynchRPC = 228,
    SyncCableCarRPC = 229,
    StartPlantingBomb = 230,
    ResetPlantingBomb = 231,
    StartDefusingBomb = 232,
    ResetDefusingBomb = 233,
    SetIsPaidTransport = 234,
    SyncOwnerTransport = 235,
    SyncCharIdRPC = 236,
    SyncTeammateRegenByMe = 237,
    BossSpawned = 238,
    NewPlayerFillSafe = 239,
    SetPlayerWantedRPC = 240
};